# Copyright (C) 2017 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
os:
  - linux
  - osx
dist: trusty
services:
  - docker

git:
  depth: 50

env:
  global:
    - CFLAGS='-g -pipe'
    # This is FUZZIT_API_KEY
    - secure: "vG1NQmbuRFtWs8t2TzjgwoFjlLu97Z4chzzN7oUndnOm0tf4dQHSpgP9IjlQb6vpC9NSrwuzfPP0q0E1VOcT+X6wTytG4MhdZAJq6rJidOXaKRE359q3TBNt55P/VwY9ZE2DI6DoRw+1HnyLK5jWWWw8RtrmNY39gfE6A6uTYQrpFi3pL9KIa6hIZq1+rQhrb7mKKt69sjqbXlj9mN/DVVyqLq1m1ONIdqsGHv+8LKK0KDiexhqj7Nyazs2ZPZ9PBZKhOYm01Wq3F3ef0JAdPM9pJbxwUU1JhTqGtRs5ErWZrO4AZe5KNm1xH2+VeZl3xDxRN+7IqUwujHFcFT4kWXTb16GJ+UVNtTj6v5zbB3OCmPYMg1dXwzzW+Am0K2FFfS4A9QeMM+9vcHi2LVA/foOD2LS6ohCtCJc1kmIDJqBmSNCYliTGhSBOWJ30gqxWiMzw0UGP2ZttEBqns6PzRsHImPFRAEFelgz8nR6Ubuuj/kas6npO5oVMKkH8Kb7f/Y4PQuerTksrRY6GNYmFqvVeW1X0XmfAlKWzLcJY0g3B+FunTss06CxcWMiyZBNS/3IJLIJ1u60jxINWvqCu/xGPD9a+qkeKZNCw8rsBvNv6gX2wpmu23qQxCm6T/LN1tYTDhe6oV5QQzQAQAl1UcH7CCePar/TdcvKXqfXVeUI="
  matrix:
    - MODE=cmake-oos
    - MODE=cppcheck
    - MODE=distcheck
    - MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=address

matrix:
  include:
    - os: linux
      env: MODE=clang-format
    - os: linux
      env: MODE=cmake-oos CMAKE_ARGS=-DXML_ATTR_INFO=ON
    - os: linux
      env: MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=address CONFIGURE_ARGS="--enable-xml-attr-info --enable-fuzztargets"
    - os: linux
      env: MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=memory CONFIGURE_ARGS=--enable-fuzztargets
    - os: linux
      env: MODE=qa-sh QA_COMPILER=clang CC=clang CXX=clang++ LD=clang++ QA_SANITIZER=undefined
    - os: linux
      env: MODE=qa-sh QA_COMPILER=gcc CC=gcc CXX=g++ LD=ld QA_PROCESSOR=gcov
    - os: linux
      env: MODE=qa-sh QA_COMPILER=gcc CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ LD=i686-w64-mingw32-ld QA_PROCESSOR=gcov CONFIGURE_ARGS="--host=i686-w64-mingw32 --enable-xml-attr-info"
    - os: linux
      env: MODE=qa-sh QA_COMPILER=gcc CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ LD=i686-w64-mingw32-ld QA_PROCESSOR=gcov CONFIGURE_ARGS="--host=i686-w64-mingw32 --enable-xml-attr-info CPPFLAGS=-DXML_UNICODE_WCHAR_T"

addons:
  homebrew:
    update: true
    brewfile: true
  apt:
    sources:
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
    packages:
      - clang-9
      - clang-format-9
      - cmake
      - cppcheck
      - docbook2x
      - dos2unix
      - lzip
      - mingw-w64
      - moreutils
      - rpm
      - wine

script:
  - ./.travis.sh
